-- AgriDrone Guardian — add per-mission storage folder
-- Run in Supabase Dashboard -> SQL Editor (or via Supabase MCP).
--
-- This migration introduces a `storage_folder` column on `flights` and
-- denormalises it onto `flight_patches` so the Photos screen can group
-- patches by mission without an extra join. The folder name follows
-- the format `mission_YYYYMMDD_HHMMSS_<shortuuid>` and is generated by
-- the FastAPI backend in flight_batch.create_flight_record.

alter table public.flights
  add column if not exists storage_folder text;

create index if not exists idx_flights_storage_folder
  on public.flights (storage_folder);

alter table public.flight_patches
  add column if not exists storage_folder text;

create index if not exists idx_flight_patches_storage_folder
  on public.flight_patches (storage_folder);
